name: Build and Push Docker Image
run-name: ${{ github.actor }} is building Docker image ğŸ³
on: [push]

jobs:
  build-and-push:
    runs-on: gar-listner
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Build & Push with Kaniko
        uses: aevea/action-kaniko@v0.12.0
        with:
          image: ghcr.io/${{ github.repository }}
          tag: latest
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
