name: Build and Push Docker Image
run-name: ${{ github.actor }} is building Docker image ğŸ³
on: [push]

jobs:
  build-and-push:
    runs-on: gar-listner
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Build & Push with Kaniko (K8s-native)
        run: |
          kubectl run kaniko-build \
            --rm -i \
            --image=gcr.io/kaniko-project/executor:latest \
            --restart=Never \
            -- \
            --context=git://github.com/${{ github.repository }}.git \
            --destination=ghcr.io/${{ github.repository }}:latest
